name: Bug Report
description: Report a bug or unexpected behavior
title: "[BUG] "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear description of the bug
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should have happened
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the issue
      placeholder: |
        1. Deploy with config...
        2. SSH into instance...
        3. Run...
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs or Error Messages
      render: shell
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Environment, AWS region, instance type, etc.
    validations:
      required: false
